name: Deploy
on:
  # Trigger deploy when pushing in main.
  push:
    branches:
      - main
jobs:
  ght-bar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create .env
        env:
          VARS_JSON: ${{ toJSON(vars) }}
        run: |
          echo "$VARS_JSON" | jq -r 'keys[] as $k | "\($k)=\(.[$k])"' >> .env
#          echo DB_ROOT_PASSWORD=${{ secrets.DB_ROOT_PASSWORD }} >> .env
#          echo S3_ROOT_PASSWORD=${{ secrets.S3_ROOT_PASSWORD }} >> .env
#          echo IMGPROXY_KEY=${{ secrets.IMGPROXY_KEY }} >> .env
#          echo IMGPROXY_SALT=${{ secrets.IMGPROXY_SALT }} >> .env
#          echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env
      - name: Show .env
        run: cat .env
      - name: Start Deployment without copy
        uses: wshihadeh/docker-deployment-action@v2
        with:
          remote_docker_host: ${{ format('{0}@{1}', vars.USER, vars.HOST) }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
          args: up -d
