name: Deploy
on:
  # Trigger deploy when pushing in main.
  push:
    branches:
      - main
jobs:
  ght-bar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create .env
        env:
          VARS_JSON: ${{ toJSON(vars) }}
          SECRET_JSON: ${{ toJSON(secrets) }}
        run: |
          echo "$VARS_JSON" | jq -r 'keys[] as $k | "\($k)=\(.[$k])"' >> .env
          echo "$SECRET_JSON" | jq -r 'keys[] as $k | "\($k)=\(.[$k])"' >> .env
      - name: Start Deployment without copy
        uses: wshihadeh/docker-deployment-action@master
        with:
          remote_docker_host: ${{ secrets.HOST }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
          args: up -d
