name: Deploy
on:
  # Trigger deploy when pushing in main.
  push:
    branches:
      - main
jobs:
  ght-bar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add secrets to .env
        uses: shine1594/secrets-to-env-action@master
        with:
          secrets: ${{ toJSON(secrets) }}
          secrets_env: production
      - name: Add variables .env
        env:
          VARS_JSON: ${{ toJSON(vars) }}
        run: |
          echo "$VARS_JSON" | jq -r 'keys[] as $k | "\($k)=\(.[$k])"' >> .env
#          echo DB_ROOT_PASSWORD=${{ secrets.DB_ROOT_PASSWORD }} >> .env
#          echo S3_ROOT_PASSWORD=${{ secrets.S3_ROOT_PASSWORD }} >> .env
#          echo IMGPROXY_KEY=${{ secrets.IMGPROXY_KEY }} >> .env
#          echo IMGPROXY_SALT=${{ secrets.IMGPROXY_SALT }} >> .env
#          echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env
      - name: Replace variables in .env
        uses: falnyr/replace-env-vars-action@master
        env:
          DB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
          DB_NAME: ${{ vars.DB_NAME }}
          S3_FOLDER_IMAGES: ${{ vars.S3_FOLDER_IMAGES }}
          S3_BUCKET: ${{ vars.S3_BUCKET }}
          S3_PATH_IMAGE: ${{ vars.S3_PATH_IMAGE }}
        with:
          filename: .env
      - name: Show .env
        run: cat .env
      - name: Start Deployment without copy
        uses: wshihadeh/docker-deployment-action@v2
        with:
          remote_docker_host: ${{ format('{0}@{1}', vars.USER, vars.HOST) }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
          args: up -d --build
